package me.matthorn.euler.euler012;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/*The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?*/

public class Program
{
	public static void main(String[] args)
	{
		long tri = 0, k = 1;
		while (k <= 7)
		{
			System.out.printf("%d has %d factors.\n", (tri += k++), factorCount(tri));
		}
	}
	
	private static int factorCount(long n)
	{
		if (n < 1)
			return 0;
		else if (n == 1)
			return 1;
		
		int count = 2;	// 1 and n to start with
		final long LIMIT = n / 2;
		for (long i = 2; i <= LIMIT; ++i)
		{
			if (n % i == 0)
			{
				// If i^2 = n, there's only one factor
				if (i * i == n)
					count++;
				else
					count += 2;
			}
		}
		return count;
	}
}
